### ISSUE TITLE
Enhancement: Sprint button only works while walking

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [AnimatedSwine37/p4gpc.tinyadditions#2]
self explanatory, pressing `b` in menus still toggles sprint
make it not do that

**Comment by AnimatedSwine37** [comment]
This is fixed with 299f68d702464c467063acd7a40554f37f86afe1 which stops sprint from being toggled when in menus.
It still can be toggled whilst not walking but mainly due to controller input this will be left as is for now.
